import {TaskContent} from './task-content';

export const TASKCONTENT : TaskContent[] =[
  {id:1,day_of_week:0,title:'掃除',detail:'',group_id:'group1',icon_id:'../assets/image/basket.png', assign_user:"sono",comment:""},
  {id:2,day_of_week:0,title:'洗濯',detail:'',group_id:'group1',icon_id:'../assets/image/broom.png', assign_user:"taka",comment:""},
  {id:3,day_of_week:0,title:'なかし',detail:'',group_id:'group1',icon_id:'../assets/image/function.png', assign_user:"hiro",comment:""},
  {id:4,day_of_week:0,title:'掃除',detail:'',group_id:'group1',icon_id:'../assets/image/glass.png', assign_user:"sono",comment:""},
  {id:5,day_of_week:0,title:'洗濯',detail:'',group_id:'group1',icon_id:'../assets/image/gloup.png', assign_user:"saito",comment:""},
  {id:6,day_of_week:0,title:'なかし',detail:'',group_id:'group1',icon_id:'../assets/image/golf.png', assign_user:"katuma",comment:""},
  {id:7,day_of_week:0,title:'洗濯物取り込み',detail:'',group_id:'group1',icon_id:'../assets/image/gorintou.png', assign_user:"katu",comment:""},
  {id:8,day_of_week:0,title:'勝間',detail:'',group_id:'group1',icon_id:'../assets/image/hideyo.png', assign_user:"ma",comment:""},
  {id:9,day_of_week:0,title:'カツマー',detail:'',group_id:'group2',icon_id:'../assets/image/house.png', assign_user:"sa",comment:""},
  {id:10,day_of_week:0,title:'テスト',detail:'',group_id:'group2',icon_id:'../assets/image/kouji.png', assign_user:"ttt",comment:""},
  {id:11,day_of_week:1,title:'トイレ掃除',detail:'',group_id:'group2',icon_id:'../assets/image/house.png', assign_user:"toto",comment:""},
  {id:11,day_of_week:1,title:'水風呂',detail:'',group_id:'group2',icon_id:'../assets/image/function.png', assign_user:"ccc",comment:""},
  {id:11,day_of_week:1,title:'クッキー焼き',detail:'',group_id:'group2',icon_id:'../assets/image/golf.png', assign_user:"bbb",comment:""},
  {id:11,day_of_week:1,title:'だるま落とし',detail:'',group_id:'group2',icon_id:'../assets/image/golf.png', assign_user:"aaa",comment:""},
  {id:12,day_of_week:2,title:'なかしは酒を飲む',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"muda",comment:""},
  {id:12,day_of_week:2,title:'発散',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pory",comment:""},
  {id:12,day_of_week:2,title:'カラオケ',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"hoge",comment:""},
  {id:12,day_of_week:2,title:'ブッラッシング',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"kuru",comment:""},
  {id:13,day_of_week:3,title:'酒を買ってこい',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"fuga",comment:""},
  {id:14,day_of_week:4,title:'なんだこのタスク',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:""},
  {id:14,day_of_week:4,title:'え？',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:""},
  {id:14,day_of_week:4,title:'これ',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:""},
  {id:14,day_of_week:4,title:'なに？',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:""},
  {id:14,day_of_week:4,title:'なるほど',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:""},
  {id:14,day_of_week:4,title:'なるほだない',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"pro",comment:"ああああああああああああああああああああ"},
  {id:15,day_of_week:5,title:'乃木坂',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"ama",comment:""},
  {id:16,day_of_week:6,title:'欅坂',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"nyu",comment:""},
  {id:17,day_of_week:6,title:'46',detail:'',group_id:'group3',icon_id:'../assets/image/golf.png', assign_user:"te",comment:""},
];
